--CREATINF THE TABLES;

CREATE TABLE MOVIES 
(
MOVIE_ID INT,
MOVIE_NAME VARCHAR(255),
MOVIE_GENRE VARCHAR(255),
MOVIE_ACTOR VARCHAR(255),
MOVIE_RATING VARCHAR(255),
MOVIE_RELEASE_DATE DATE
)


CREATE TABLE ACTORS 
(
ACTOR_ID INT,
ACTOR_NAME VARCHAR(255),
CITIZENSHIP VARCHAR(255),
MOVIE_ID INT,
ACTOR_GENRE VARCHAR(255),
ACTOR_RATING VARCHAR(255),
GENDER VARCHAR(255)
)


CREATE TABLE GENRE_TYPE 
(
GENRE_ID INT,
GENRE_NAME VARCHAR(255),
MOVIE_ID INT,
)

CREATE TABLE MOVIE_SALES 
(
SALE_ID INT,
SALE_NAME VARCHAR(255),
SALE_TYPE VARCHAR(255),
SALE_AMOUNT INT,
SALE_DATE DATE,
SALE_STATUS VARCHAR(255)
)

---
SELECT * FROM MOVIES;

SELECT * FROM GENRE;

SELECT * FROM MOVIE_SALES;

SELECT * FROM GENRE_TYPE;

--

SELECT MOVIE NAME WHERE MOVIE_ACTOR = 'MALE';


SELECT * FROM MOVIE_SALES WHERE SALE_AMOUNT > 5000 
AND SALE_DATE > '2019-01-01'

---

SELECT a.MOVIE_NAME, a.MOVIE_ACTOR, b.SALE_AMOUNT FROM MOVIES a 
LEFT OUTER JOIN MOVIE_SALES b 
ON a.MOVIE_ID = b. MOVIE_ID 
WHERE SALE_DATE >= '2020-03-01'
AND MOVIE_RATING = 'GOOD'