CREATE TABLE MATCH 
(
MATCH_CODE VARCHAR(255) PRIMARY NOT NULL,
MATCH_DATE TIMESTAMP,
NO_OF_PLAYERS INT,
SCORE INT,
PRIMARY KEY (MATCH_CODE),
FOREIGN KEY (REF_ID) REFERENCES REFEREE(REF_ID)
);

CREATE TABLE PLAYERS
(
PASSPORT_NUM VARCHAR(255) PRIMARY NOT NULL,
PLAYER_NAME VARCHAR(255),
MACTH_ID INT,
NATIONALITY VARCHAR(255)
PRIMARY KEY (PASSPORT_NUM),
FOREIGN KEY (MATCH_CODE) REFERENCES MATCH(MATCH_CODE)
);

CREATE TABLE REFEREE
(
REF_ID INT PRIMARY NOT NULL,
REF_NAME VARCHAR(255),
MACTH_ID INT,
NATIONALITY VARCHAR(255)
PRIMARY KEY (PASSPORT_NUM),
FOREIGN KEY (REF_ID) REFERENCES MATCH(MATCH_CODE)
);