--READ FROM THE TABLES 

SELECT * FROM SHIPPERS;
SELECT * FROM SUPPLERS;
SELECT * FROM EMPLOYEES_TABLE;
SELECT * FROM PRODUCTS;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM ORDERDETAILS;

SELECT a.ORDER_ID,a.QUANTITY,c.PRODUCT_ID,c.REORDER_LEVEL,  FROM ORDERS a
LEFT OUTER JOIN ORDERDETAILS b
ON a.ORDER_ID = b.ORDER_ID
LEFT OUTER JOIN PRODUCTS c 
ON b.PRODUCT_ID = c.PRODUCT_ID
LEFT OUTER JOIN SUPPLIERS d 
c.SUPPLIER_ID = c.SUPPLIER_ID 
WHERE b.QUANTITY > 65 AND b.QUANTITY >75
ORDER BY ORDER_ID ASC

---------------------------------------------

SELECT a.PRODUCT_ID, a.PRODUCT_NAME,
a.ENGLISH_NAME,a.UNIT_PRICE FROM PRODUCTS a 
WHERE a.UNIT_PRICE <80
ORDER BY a.PRODUCT_ID ASC

-----------------------------------------------------

SELECT CUSTOMER_ID, COMPANY_NAME,COUNTRY, PHONE
FROM  CUSTOMERS WHERE COUNTRY LIKE '%CANADA%' OR COUNTRY LIKE '%USA%'
ORDER BY PHONE ASC


--------------------------------------------------------
SELECT a.SUPPLIER_ID,a.SUPPLIER_NAME,b.PRODUCT_NAME,
sum(b.REORDER_LEVEL),sum(b.UNITS_INSTOCK) FROM PRODUCTS a
LEFT OUTER JOIN SUPPLIERS b 
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE sum(b.REORDER_LEVEL) = sum(b.UNITS_INSTOCK) 
ORDER BY b.SUPPLIER_ID ASC

--------------------------------------------------------------

SELECT a.ORDER_ID, b.COMPANY_NAME, b.CONTACT_NAME, TO_CHAR(a.SHIPPED_DATE,'YYYY-MM-DD'),
CASE WHEN
'2009-01-01' MINUS TO_CHAR(a.SHIPPED_DATE,'YYYY-MM-DD') THEN COUNT(YEAR('2009-01-01' MINUS TO_CHAR(a.SHIPPED_DATE,'YYYY-MM-DD')))
FROM ORDERS a 
LEFT OUTER JOIN CUSTOMERS b 
ON a.ORDER_ID = b.ORDER_ID
WHERE TO_CHAR(a.SHIPPED_DATE,'YYYY-MM-DD') >= '01-01-1994'
ORDER BY a.ORDER_ID ASC


-------------------------------------------------------------------------------

SELECT a.ORDER_ID, b.PRODUCT_NAME,c.COMPANY_NAME,a.ORDER_DATE,
CASE WHEN (DAY(TO_CHAR(a.SHIPPED_DATE,'YYYY-MM-DD'))) + 10 THEN 'NEWSHIPPED_DATE',
(a.QUANTITY*a.UNIT_PRICE)ORDER_COST
FROM ORDERS a 
LEFT OUTER JOIN PRODUCTS b
on a.PRODUCT_ID = b.PRODUCT_ID
LEFT OUTER JOIN CUSTOMERS
ON a.CUSTOMER_ID = c.CUSTOMER_ID
WHERE a.ORDER_DATE >= '01-01-1992' AND a.ORDER_DATE <= '30-03-1992'
ORDER BY a.ORDER_ID ASC


--------------------------------------------------------------------------------

SELECT a.ORDER_ID, a.UNIT_PRICE, a.QUANTITY FROM ORDERDETAILS a
LEFT OUTER JOIN CUSTOMERS b 
ON a.ORDER_ID = b.a.ORDER_ID
WHERE b.CUSTOMERS = 'VANCOUVER'
ORDER BY a.ORDER_ID ASC


-------------------------------------------------------------

SELECT a.CUSTOMER_ID,a.COMPANY_NAME,a.FAX,b.ORDER_ID,b.ORDER_DATE
FROM CUSTOMERS a
LEFT OUTER JOIN ORDERS b 
ON a.ORDER_ID = b.ORDER_ID 
ORDER BY b.ORDER_ID ASC

------------------------------------------------------------

SELECT a.PRODUCT_ID, a.PRODUCT_NAME,a.QUANTITYPERUNIT,a.UNIT_PRICE
FROM PRODUCTS a
WHERE PRODUCT_NAME LIKE '%TOFU' AND PRODUCT_NAME LIKE '%CHOFU%'
ORDER BY a.PRODUCT_ID ASC

SELECT LEFT(PRODUCT_NAME, 1), COUNT(*) FROM PRODUCTS
GROUP BY PR


