--CREATING THE OWNER AND PET INFO 

CREATE TABLE OWNER_PET_INFO 
(
OWNER_ID INT NOT NULL,
OWNER_NAME VARCHAR(255),
PET_NAME VARCHAR(255),
OWNER_ADDRESS VARCHAR(255),
PET_ID INT NOT NULL,
PET_DESCRIPTION VARCHAR(255)
)

INSERT INTO OWNER_PET_INFO (OWNER_ID,OWNER_NAME,PET_NAME,OWNER_ADDRESS,PET_ID,PET_DESCRIPTION)
VALUES('1','SCOTT, BRUCE','COCKER SPANIEL','200 LEMON DRIVE','1',' F, 5 yr., 28 lbs');

--APPONTMNENT TABLE 

CREATE TABLE APPOINTMENT_PET_INFO 
(
OWNER_ID INT NOT NULL,
OWNER_NAME VARCHAR(255),
PET_NAME VARCHAR(255),
APPOINTMENT_INFO VARCHAR(255),
PET_ID INT NOT NULL,
PET_DESCRIPTION VARCHAR(255),
APPOINTMENT_DATE DATE
)

INSERT INTO APPOINTMENT_PET_INFO (OWNER_ID,OWNER_NAME,PET_NAME,APPOINTMENT_INFO,PET_ID,PET_DESCRIPTION,APPOINTMENT_DATE)
VALUES('1','SCOTT BRUCE', 'COCKER SPANIEL','DELUXE GROOM','1', 'TEETH BRUSHING','2019-07-19');

CREATE TABLE INVOICE_INFO 
(
OWNER_ID INT NOT NULL,
OWNER_NAME VARCHAR(255),
PET_ID INT NOT NULL,
PET_DESCRIPTION VARCHAR(255),
SERVICE_TYPE VARCHAR(255),
AMOUNT_TOTAL FLOAT,
INVOICE_DECSRIPTION VARCHAR(255),
SERVICE_DATE DATE
)

INSERT INTO INVOICE_INFO (OWNER_ID,OWNER_NAME,PET_ID,PET_DESCRIPTION,SERVICE_TYPE,AMOUNT_TOTAL,INVOICE_DECSRIPTION,SERVICE_DATE)
VALUES('1','SCOTT BRUCE','1','F, 5 yr., 28 lbs','TEETH BRUSHING','567','1/15/2021 1:00 PM
(1) STANDARD GROOM - $99.00 (1 hr. 30 min)
(2) TEETH BRUSHING - $39.00 (30 min.)
TOTAL: $138.00 (2 hrs.)
','2018-05-23');